--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.34.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 08/09/2023 0:38:43
-- Server version: 8.0.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE dbmysqlserver;

--
-- Drop table `customers`
--
DROP TABLE IF EXISTS customers;

--
-- Set default database
--
USE dbmysqlserver;

--
-- Create table `customers`
--
CREATE TABLE customers (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) DEFAULT NULL,
  apellido VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  dni VARCHAR(255) DEFAULT NULL,
  fecha_nacimiento DATE DEFAULT NULL,
  fecha_creacion DATE DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM,
AUTO_INCREMENT = 6,
CHARACTER SET utf8mb4,
CHECKSUM = 0,
COLLATE utf8mb4_spanish_ci;

-- 
-- Dumping data for table customers
--
INSERT INTO customers VALUES
(1, 'Isabel', 'Mendoza Prado', 'isabel.mendoza@domain.com', '45986235', '1992-09-05', '2023-09-07'),
(2, 'Clara', 'Salazar Gomez', 'clara.salazar@dominio.com', '44556863', '1859-06-19', '2023-09-07'),
(3, 'Sofia', 'Vergara Terry', 'sofia.vergara@domain.com', '45896576', '1805-03-01', '2023-09-07'),
(4, 'Sofia', 'Vergara Terry', 'sofia.vergara@domain.com', '45896236', '1805-03-01', '2023-09-07'),
(5, 'Daniela', 'Martinez Praado', 'daniela.martinez@domain.com', '45896235', '1995-03-01', '2023-09-07');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;